In [1]:
import json
import spacy
from spacy.tokens import DocBin
from spacy.training import Example

In [2]:
f =open("/tf/empty_homes_data/humanloop_spacy_format.json")  #aggregate and download button

# returns JSON object as 
# a dictionary
data = json.load(f)

In [13]:
data

[{'datapoint_id': 0,
  'text': 'westleigh lodge care home, nel pan lane, leigh (wn7 5jt)',
  'entities': [[0, 25, 'building_name'],
   [27, 39, 'street_name'],
   [41, 46, 'city'],
   [48, 55, 'postcode']]},
 {'datapoint_id': 1,
  'text': 'flat 1, 1a canal street, manchester (m1 3he)',
  'entities': [[0, 4, 'unit_type'],
   [5, 6, 'unit_id'],
   [8, 10, 'street_number'],
   [11, 23, 'street_name'],
   [25, 35, 'city'],
   [37, 43, 'postcode']]},
 {'datapoint_id': 2,
  'text': 'flat 201, 1 regent road, manchester (m3 4ay)',
  'entities': [[0, 4, 'unit_type'],
   [5, 8, 'unit_id'],
   [10, 11, 'street_number'],
   [12, 23, 'street_name'],
   [25, 35, 'city'],
   [37, 43, 'postcode']]},
 {'datapoint_id': 3,
  'text': 'land at 2a gerard street, ashton in makerfield, wigan (wn4 9aa)',
  'entities': [[0, 4, 'unit_type'],
   [11, 24, 'street_name'],
   [48, 53, 'city'],
   [55, 62, 'postcode']]},
 {'datapoint_id': 4,
  'text': 'unit 111, timber wharf, worsley street, manchester (m15 4nz)',
  'entities': [[0, 4, 'unit_type'],
   [5, 8, 'unit_id'],
   [10, 23, 'building_name'],
   [24, 38, 'street_name'],
   [40, 50, 'city'],
   [52, 59, 'postcode']]},
 {'datapoint_id': 5,
  'text': '81 hawksbill way, peterborough (pe2 8ns)',
  'entities': [[0, 2, 'street_number'],
   [3, 16, 'street_name'],
   [18, 30, 'city'],
   [32, 39, 'postcode']]},
 {'datapoint_id': 6,
  'text': '3 beluga close, peterborough (pe2 8nr)',
  'entities': [[0, 1, 'street_number'],
   [2, 14, 'street_name'],
   [16, 28, 'city'],
   [30, 37, 'postcode']]},
 {'datapoint_id': 7,
  'text': '232 hawksbill way, peterborough and parking space (pe2 8ny)',
  'entities': [[0, 3, 'street_number'],
   [4, 17, 'street_name'],
   [19, 49, 'city'],
   [51, 58, 'postcode']]},
 {'datapoint_id': 8,
  'text': 'land at cityscape, high street, peterborough',
  'entities': [[0, 4, 'unit_type'],
   [19, 30, 'street_name'],
   [32, 44, 'city']]},
 {'datapoint_id': 9,
  'text': 'land at queensgate centre, peterborough',
  'entities': [[0, 4, 'unit_type'],
   [8, 25, 'building_name'],
   [27, 39, 'city']]},
 {'datapoint_id': 10,
  'text': '51 beluga close, peterborough (pe2 8nr)',
  'entities': [[0, 2, 'street_number'],
   [3, 15, 'street_name'],
   [17, 29, 'city'],
   [31, 38, 'postcode']]},
 {'datapoint_id': 11,
  'text': '121 hawksbill way, peterborough (pe2 8ns)',
  'entities': [[0, 3, 'street_number'],
   [4, 17, 'street_name'],
   [19, 31, 'city'],
   [33, 40, 'postcode']]},
 {'datapoint_id': 12,
  'text': '44 beluga close, peterborough (pe2 8ne)',
  'entities': [[0, 2, 'street_number'],
   [3, 15, 'street_name'],
   [17, 29, 'city'],
   [31, 38, 'postcode']]},
 {'datapoint_id': 13,
  'text': '2-24 (even) miller way, 15-25 hammonds drive (odd) and 1-19 rudd close (odd) fengate, peterborough',
  'entities': [[0, 4, 'street_number'],
   [6, 10, 'number_filter'],
   [12, 22, 'street_name'],
   [24, 29, 'street_number'],
   [30, 44, 'street_name'],
   [46, 49, 'number_filter'],
   [55, 59, 'street_number'],
   [60, 70, 'street_name'],
   [72, 75, 'number_filter'],
   [77, 84, 'street_name'],
   [86, 98, 'city']]},
 {'datapoint_id': 14,
  'text': '155 hawksbill way, peterborough (pe2 8ns)',
  'entities': [[0, 3, 'street_number'],
   [4, 17, 'street_name'],
   [19, 31, 'city'],
   [33, 40, 'postcode']]},
 {'datapoint_id': 15,
  'text': '61 beluga close, peterborough (pe2 8nr)',
  'entities': [[0, 2, 'street_number'],
   [3, 15, 'street_name'],
   [17, 29, 'city'],
   [31, 38, 'postcode']]},
 {'datapoint_id': 16,
  'text': '139 hawksbill way, peterborough (pe2 8ns)',
  'entities': [[0, 3, 'street_number'],
   [4, 17, 'street_name'],
   [19, 31, 'city'],
   [33, 40, 'postcode']]},
 {'datapoint_id': 17,
  'text': 'the grafton centre, cambridge',
  'entities': [[0, 18, 'building_name'], [20, 29, 'street_name']]},
 {'datapoint_id': 18,
  'text': '157 hawksbill way, peterborough (pe2 8ns)',
  'entities': [[0, 3, 'street_number'],
   [4, 17, 'street_name'],
   [19, 31, 'city'],
   [33, 40, 'postcode']]},
 {'datapoint_id': 19,
  'text': '286 hawksbill way, peterborough (pe2 8ny)',
  'entities': [[0, 3, 'street_number'],
   [4, 17, 'street_name'],
   [19, 31, 'city'],
   [33, 40, 'postcode']]},
 {'datapoint_id': 20,
  'text': '88 great northern road, cambridge cb1 2fx',
  'entities': [[0, 2, 'street_number'],
   [3, 22, 'street_name'],
   [24, 33, 'city'],
   [34, 41, 'postcode']]},
 {'datapoint_id': 21,
  'text': '73 sheffield road, birdwell, barnsley (s70 5xf)',
  'entities': [[0, 2, 'street_number'],
   [3, 17, 'street_name'],
   [29, 37, 'city'],
   [39, 46, 'postcode']]},
 {'datapoint_id': 22,
  'text': '79 sheffield road, birdwell, barnsley (s70 5xf)',
  'entities': [[0, 2, 'street_number'],
   [3, 17, 'street_name'],
   [29, 37, 'city'],
   [39, 46, 'postcode']]},
 {'datapoint_id': 23,
  'text': '185 sheffield road, birdwell, barnsley (s70 5tj)',
  'entities': [[0, 3, 'street_number'],
   [4, 18, 'street_name'],
   [30, 38, 'city'],
   [40, 47, 'postcode']]},
 {'datapoint_id': 24,
  'text': '211 sheffield road, birdwell, barnsley (s70 5tj)',
  'entities': [[0, 3, 'street_number'],
   [4, 18, 'street_name'],
   [30, 38, 'city'],
   [40, 47, 'postcode']]},
 {'datapoint_id': 25,
  'text': '298 sheffield road, birdwell, barnsley (s70 5tg)',
  'entities': [[0, 3, 'street_number'],
   [4, 18, 'street_name'],
   [30, 38, 'city'],
   [40, 47, 'postcode']]},
 {'datapoint_id': 26,
  'text': '266 sheffield road, birdwell, barnsley (s70 5tf)',
  'entities': [[0, 3, 'street_number'],
   [4, 18, 'street_name'],
   [30, 38, 'city'],
   [40, 47, 'postcode']]},
 {'datapoint_id': 27,
  'text': 'apartment 223, daisy spring works, 1 dun street, sheffield (s3 8dr)',
  'entities': [[0, 9, 'unit_type'],
   [10, 13, 'unit_id'],
   [35, 36, 'street_number'],
   [37, 47, 'street_name'],
   [49, 58, 'city'],
   [60, 66, 'postcode']]},
 {'datapoint_id': 28,
  'text': 'units 4 and 6, callflex business park, doncaster road, wath upon dearne, rotherham (s63 7ef)',
  'entities': [[0, 4, 'unit_type'],
   [6, 7, 'unit_id'],
   [39, 53, 'street_name'],
   [73, 82, 'city'],
   [84, 91, 'postcode']]},
 {'datapoint_id': 29,
  'text': '274 sheffield road, birdwell, barnsley (s70 5tg)',
  'entities': [[0, 3, 'street_number'],
   [4, 18, 'street_name'],
   [30, 38, 'city'],
   [40, 47, 'postcode']]},
 {'datapoint_id': 30,
  'text': 'land and buildings on the north east side of surbiton street, sheffield',
  'entities': [[0, 4, 'unit_type'],
   [45, 60, 'street_name'],
   [62, 71, 'city']]},
 {'datapoint_id': 31,
  'text': 'gateway plaza hotel, sackville street, barnsley, yorkshire (s70 2rd)',
  'entities': [[0, 19, 'building_name'],
   [21, 37, 'street_name'],
   [49, 58, 'city'],
   [60, 67, 'postcode']]},
 {'datapoint_id': 32,
  'text': 'apartment 210, daisy spring works, 1 dun street, sheffield (s3 8dr)',
  'entities': [[0, 9, 'unit_type'],
   [10, 13, 'unit_id'],
   [35, 36, 'street_number'],
   [37, 47, 'street_name'],
   [49, 58, 'city'],
   [60, 66, 'postcode']]},
 {'datapoint_id': 33,
  'text': 'apartment 132, daisy spring works, 1 dun street, sheffield (s3 8dr)',
  'entities': [[0, 9, 'unit_type'],
   [10, 13, 'unit_id'],
   [35, 36, 'street_number'],
   [37, 47, 'street_name'],
   [49, 58, 'city'],
   [60, 66, 'postcode']]},
 {'datapoint_id': 34,
  'text': 'apartment 317, daisy spring works, 1 dun street, sheffield (s3 8du)',
  'entities': [[0, 9, 'unit_type'],
   [10, 13, 'unit_id'],
   [35, 36, 'street_number'],
   [37, 47, 'street_name'],
   [49, 58, 'city'],
   [60, 66, 'postcode']]},
 {'datapoint_id': 35,
  'text': 'unit 2, smithy wood drive, smithy wood business park, sheffield (s35 1qn)',
  'entities': [[0, 4, 'unit_type'],
   [5, 6, 'unit_id'],
   [8, 25, 'street_name'],
   [54, 63, 'city'],
   [65, 72, 'postcode']]},
 {'datapoint_id': 36,
  'text': 'airspace above 4 rotherwood crescent, thurcroft, rotherham (s66 9pp)',
  'entities': [[0, 8, 'unit_type'],
   [17, 36, 'street_name'],
   [49, 58, 'city'],
   [60, 67, 'postcode']]},
 {'datapoint_id': 37,
  'text': 'airspace above 4 lark avenue, brinsworth, rotherham (s60 5lr)',
  'entities': [[0, 8, 'unit_type'],
   [17, 28, 'street_name'],
   [42, 51, 'city'],
   [53, 60, 'postcode']]},
 {'datapoint_id': 38,
  'text': '1-25 (excluding 13) acorn way, sunnyside, rotherham (s66 3xh)',
  'entities': [[0, 4, 'street_number'],
   [20, 29, 'street_name'],
   [42, 51, 'city'],
   [53, 60, 'postcode']]},
 {'datapoint_id': 39,
  'text': 'airspace above 79 lapwater road, rotherham (s61 4lr)',
  'entities': [[0, 8, 'unit_type'],
   [18, 31, 'street_name'],
   [33, 42, 'city'],
   [44, 51, 'postcode']]},
 {'datapoint_id': 40,
  'text': 'airspace above 85 goodwin road, rotherham (s61 4dw)',
  'entities': [[0, 8, 'unit_type'],
   [18, 30, 'street_name'],
   [32, 41, 'city'],
   [43, 50, 'postcode']]},
 {'datapoint_id': 41,
  'text': 'parking space 161 moho, ellesmere street, manchester',
  'entities': [[0, 13, 'unit_type'],
   [24, 40, 'street_name'],
   [42, 52, 'city']]},
 {'datapoint_id': 42,
  'text': 'parking space 91 burton place, manchester',
  'entities': [[0, 13, 'unit_type'],
   [17, 29, 'street_name'],
   [31, 41, 'city']]},
 {'datapoint_id': 43,
  'text': 'parking space 16, chips, 2 lampwick lane, manchester (m4 6bu)',
  'entities': [[0, 13, 'unit_type'],
   [25, 26, 'street_number'],
   [27, 40, 'street_name'],
   [42, 52, 'city'],
   [54, 60, 'postcode']]},
 {'datapoint_id': 44,
  'text': '1, 4 and 5 top park close, warburton, lymm (wa13 9nz)',
  'entities': [[0, 1, 'street_number'],
   [3, 4, 'street_number'],
   [9, 10, 'street_number'],
   [11, 25, 'street_name'],
   [38, 42, 'city'],
   [44, 52, 'postcode']]},
 {'datapoint_id': 45,
  'text': '28 newbridge close, radcliffe, manchester (m26 2wb)',
  'entities': [[0, 2, 'street_number'],
   [3, 18, 'street_name'],
   [31, 41, 'city'],
   [43, 50, 'postcode']]},
 {'datapoint_id': 46,
  'text': '70 to 98 (even), weavermill park, ashton in makerfield, wigan (wn4 9ez)',
  'entities': [[0, 8, 'street_number'],
   [10, 14, 'number_filter'],
   [17, 32, 'street_name'],
   [56, 61, 'city'],
   [63, 70, 'postcode']]},
 {'datapoint_id': 47,
  'text': '3a, 5a and 8a hesketh drive, standish, wigan (wn6 0sf)',
  'entities': [[0, 2, 'street_number'],
   [4, 6, 'street_number'],
   [11, 13, 'street_number'],
   [14, 27, 'street_name'],
   [39, 44, 'city'],
   [46, 53, 'postcode']]},
 {'datapoint_id': 48,
  'text': '1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 14, 16, 18, 19, 21 and 22 heath house close, lowton, and 106 and 108 stone cross lane north, lowton, warrington',
  'entities': [[0, 1, 'street_number'],
   [3, 4, 'street_number'],
   [6, 7, 'street_number'],
   [9, 10, 'street_number'],
   [12, 13, 'street_number'],
   [15, 16, 'street_number'],
   [18, 19, 'street_number'],
   [21, 22, 'street_number'],
   [24, 25, 'street_number'],
   [27, 29, 'street_number'],
   [31, 33, 'street_number'],
   [35, 37, 'street_number'],
   [39, 41, 'street_number'],
   [43, 45, 'street_number'],
   [47, 49, 'street_number'],
   [51, 53, 'street_number'],
   [58, 60, 'street_number'],
   [61, 78, 'street_name'],
   [92, 95, 'street_number'],
   [100, 103, 'street_number'],
   [104, 126, 'street_name'],
   [136, 146, 'city']]},
 {'datapoint_id': 49,
  'text': 'southern tower, bengal mill, bengal street, manchester (m4 6af)',
  'entities': [[0, 14, 'building_name'],
   [29, 42, 'street_name'],
   [44, 54, 'city'],
   [56, 62, 'postcode']]},
 {'datapoint_id': 50,
  'text': '25 newbridge close, radcliffe, manchester (m26 2wb)',
  'entities': [[0, 2, 'street_number'],
   [3, 18, 'street_name'],
   [31, 41, 'city'],
   [43, 50, 'postcode']]},
 {'datapoint_id': 51,
  'text': '22 newbridge close, radcliffe, manchester (m26 2wb)',
  'entities': [[0, 2, 'street_number'],
   [3, 18, 'street_name'],
   [31, 41, 'city'],
   [43, 50, 'postcode']]},
 {'datapoint_id': 52,
  'text': 'unit 3, the vibe, 175 broughton lane, salford (m7 1us)',
  'entities': [[0, 4, 'unit_type'],
   [5, 6, 'unit_id'],
   [18, 21, 'street_number'],
   [22, 36, 'street_name'],
   [38, 45, 'city'],
   [47, 53, 'postcode']]},
 {'datapoint_id': 53,
  'text': 'land on the south side of cornishway, manchester',
  'entities': [[0, 4, 'unit_type'],
   [26, 36, 'street_name'],
   [38, 48, 'city']]},
 {'datapoint_id': 54,
  'text': 'land lying to the north of lodge side, bury',
  'entities': [[0, 4, 'unit_type'],
   [27, 37, 'street_name'],
   [39, 43, 'city']]},
 {'datapoint_id': 55,
  'text': 'land at partington shopping centre, central road, partington, manchester',
  'entities': [[0, 4, 'unit_type'],
   [8, 34, 'building_name'],
   [36, 48, 'street_name'],
   [62, 72, 'city']]},
 {'datapoint_id': 56,
  'text': '2 and 4 colliers grove, 16 gadfield grove, 11, 12, 16, 19, 21, 22, 24-30, 32, 33, 35-37 and 41 albion close, atherton, manchester',
  'entities': [[0, 1, 'street_number'],
   [6, 7, 'street_number'],
   [8, 22, 'street_name'],
   [24, 26, 'street_number'],
   [27, 41, 'street_name'],
   [43, 45, 'street_number'],
   [47, 49, 'street_number'],
   [51, 53, 'street_number'],
   [55, 57, 'street_number'],
   [59, 61, 'street_number'],
   [63, 65, 'street_number'],
   [67, 72, 'street_number'],
   [74, 76, 'street_number'],
   [78, 80, 'street_number'],
   [82, 87, 'street_number'],
   [92, 94, 'street_number'],
   [95, 107, 'street_name'],
   [119, 129, 'city']]},
 {'datapoint_id': 57,
  'text': '2 to 4 and 6 to 11 (inclusive), junction close, blackrod, bolton (bl6 5gn)',
  'entities': [[0, 6, 'street_number'],
   [11, 18, 'street_number'],
   [32, 46, 'street_name'],
   [58, 64, 'city'],
   [66, 73, 'postcode']]},
 {'datapoint_id': 58,
  'text': '3 and 5 bloomsbury crescent, 2, 4, 7, 9, 11, 12 and 14 burlington drive and 2, 3, 5, 14 and 16 windsor gardens, bolton',
  'entities': [[0, 1, 'street_number'],
   [6, 7, 'street_number'],
   [8, 27, 'street_name'],
   [29, 30, 'street_number'],
   [32, 33, 'street_number'],
   [35, 36, 'street_number'],
   [38, 39, 'street_number'],
   [41, 43, 'street_number'],
   [45, 47, 'street_number'],
   [52, 54, 'street_number'],
   [55, 71, 'street_name'],
   [76, 77, 'street_number'],
   [79, 80, 'street_number'],
   [82, 83, 'street_number'],
   [85, 87, 'street_number'],
   [92, 94, 'street_number'],
   [95, 110, 'street_name'],
   [112, 118, 'city']]},
 {'datapoint_id': 59,
  'text': '59 and 71 lawnhurst avenue, apartment 8, 240 lawnhurst avenue, apartments 3, 8 and 13, 242 lawnhurst avenue, apartment 6, 244 lawnhurst avenue, apartments 4 and 9, 246 lawnhurst avenue and apartment 13, 248 lawnhurst avenue, wythenshawe, manchester',
  'entities': [[0, 2, 'unit_id'],
   [7, 9, 'unit_id'],
   [10, 26, 'street_name'],
   [28, 37, 'unit_type'],
   [38, 39, 'unit_id'],
   [41, 44, 'street_number'],
   [45, 61, 'street_name'],
   [77, 78, 'street_number'],
   [83, 85, 'unit_id'],
   [87, 90, 'street_number'],
   [91, 107, 'street_name'],
   [109, 118, 'unit_type'],
   [119, 120, 'unit_id'],
   [122, 125, 'street_number'],
   [126, 142, 'street_name'],
   [155, 156, 'unit_id'],
   [164, 167, 'street_number'],
   [168, 184, 'street_name'],
   [189, 198, 'unit_type'],
   [199, 201, 'unit_id'],
   [203, 206, 'street_number'],
   [207, 223, 'street_name'],
   [238, 248, 'city']]},
 {'datapoint_id': 60,
  'text': 'keerford view, 152 lancaster road, carnforth (la5 9ee)',
  'entities': [[0, 13, 'building_name'],
   [15, 18, 'street_number'],
   [19, 33, 'street_name'],
   [35, 44, 'city'],
   [46, 53, 'postcode']]},
 {'datapoint_id': 61,
  'text': 'bingo hall, waterside centre, saltergate, lincoln (ln2 1dh)',
  'entities': [[0, 10, 'building_name'],
   [12, 28, 'building_name'],
   [30, 40, 'street_name'],
   [42, 49, 'city'],
   [51, 58, 'postcode']]},
 {'datapoint_id': 62,
  'text': '6, 15, 16, 17, 20, 21, 22, 23, 26, 27, 29, 30, 31, 32, 33, 34, 39, 40, 41, 42 and 44 ann street, hyde (sk14 2ba)',
  'entities': [[0, 1, 'street_number'],
   [3, 5, 'street_number'],
   [7, 9, 'street_number'],
   [11, 13, 'street_number'],
   [15, 17, 'street_number'],
   [19, 21, 'street_number'],
   [23, 25, 'street_number'],
   [27, 29, 'street_number'],
   [31, 33, 'street_number'],
   [35, 37, 'street_number'],
   [39, 41, 'street_number'],
   [43, 45, 'street_number'],
   [47, 49, 'street_number'],
   [51, 53, 'street_number'],
   [55, 57, 'street_number'],
   [59, 61, 'street_number'],
   [63, 65, 'street_number'],
   [67, 69, 'street_number'],
   [71, 73, 'street_number'],
   [75, 77, 'street_number'],
   [82, 84, 'street_number'],
   [85, 95, 'street_name'],
   [97, 101, 'city'],
   [103, 111, 'postcode']]},
 {'datapoint_id': 63,
  'text': '2 almond pastures, standish, wigan (wn6 0gg)',
  'entities': [[0, 1, 'street_number'],
   [29, 34, 'city'],
   [36, 43, 'postcode']]},
 {'datapoint_id': 64,
  'text': '4 almond pastures, standish, wigan (wn6 0gg)',
  'entities': [[0, 1, 'street_number'],
   [29, 34, 'city'],
   [36, 43, 'postcode']]},
 {'datapoint_id': 65,
  'text': '10 spinners drive, worsley, manchester (m28 3ub)',
  'entities': [[0, 2, 'street_number'],
   [3, 17, 'street_name'],
   [28, 38, 'city'],
   [40, 47, 'postcode']]},
 {'datapoint_id': 66,
  'text': '12 spinners drive, worsley, manchester (m28 3ub)',
  'entities': [[0, 2, 'street_number'],
   [3, 17, 'street_name'],
   [28, 38, 'city'],
   [40, 47, 'postcode']]},
 {'datapoint_id': 67,
  'text': '1 spinners drive, worsley, manchester (m28 3ub)',
  'entities': [[0, 1, 'street_number'],
   [2, 16, 'street_name'],
   [27, 37, 'city'],
   [39, 46, 'postcode']]},
 {'datapoint_id': 68,
  'text': '23 spinners drive, worsley, manchester (m28 3ub)',
  'entities': [[0, 2, 'street_number'],
   [3, 17, 'street_name'],
   [28, 38, 'city'],
   [40, 47, 'postcode']]},
 {'datapoint_id': 69,
  'text': '21 spinners drive, worsley, manchester (m28 3ub)',
  'entities': [[0, 2, 'street_number'],
   [3, 17, 'street_name'],
   [28, 38, 'city'],
   [40, 47, 'postcode']]},
 {'datapoint_id': 70,
  'text': 'land and buildings on the west side of gaskell street, bolton',
  'entities': [[0, 4, 'unit_type'],
   [39, 53, 'street_name'],
   [55, 61, 'city']]},
 {'datapoint_id': 71,
  'text': 'land lying to the north-east of manchester road, bolton',
  'entities': [[0, 4, 'unit_type'],
   [32, 47, 'street_name'],
   [49, 55, 'city']]},
 {'datapoint_id': 72,
  'text': '7 chatsworth court, bolton and parking space (bl1 4gq)',
  'entities': [[2, 18, 'building_name'],
   [20, 44, 'city'],
   [46, 53, 'postcode']]},
 {'datapoint_id': 73,
  'text': '17 chatsworth court, bolton and parking spaces (bl1 4gq)',
  'entities': [[0, 2, 'unit_id'],
   [3, 19, 'building_name'],
   [21, 46, 'city'],
   [48, 55, 'postcode']]},
 {'datapoint_id': 74,
  'text': '8 burlington drive, bolton (bl1 4er)',
  'entities': [[0, 1, 'street_number'],
   [2, 18, 'street_name'],
   [20, 26, 'city'],
   [28, 35, 'postcode']]},
 {'datapoint_id': 75,
  'text': 'apartment 504, number one, pink, media city uk, salford (m50 2ba)',
  'entities': [[0, 9, 'unit_type'],
   [10, 13, 'unit_id'],
   [48, 55, 'city'],
   [57, 64, 'postcode']]},
 {'datapoint_id': 76,
  'text': '1 spencer house, warburton lane, partington, manchester (m31 4nj)',
  'entities': [[0, 1, 'street_number'],
   [2, 15, 'building_name'],
   [17, 31, 'street_name'],
   [45, 55, 'city'],
   [57, 64, 'postcode']]},
 {'datapoint_id': 77,
  'text': '2, 4, 8, 10 and 14 abelia road, 1, 54, 68, 70, 74, 76, 78 and 80 hydrangea close westhoughton, bolton',
  'entities': [[0, 1, 'street_number'],
   [3, 4, 'street_number'],
   [6, 7, 'street_number'],
   [9, 11, 'street_number'],
   [16, 18, 'street_number'],
   [19, 30, 'street_name'],
   [32, 33, 'street_number'],
   [35, 37, 'street_number'],
   [39, 41, 'street_number'],
   [43, 45, 'street_number'],
   [47, 49, 'street_number'],
   [51, 53, 'street_number'],
   [55, 57, 'street_number'],
   [62, 64, 'street_number'],
   [95, 101, 'city']]},
 {'datapoint_id': 78,
  'text': '1000 aviator way, manchester (m22 5tg)',
  'entities': [[0, 4, 'street_number'],

In [36]:
test =[{'datapoint_id': 0,
  'text': 'westleigh lodge care home, nel pan lane, leigh (wn7 5jt)',
  'entities': [[0, 25, 'building_name'],
   [27, 39, 'street_name'],
   [41, 46, 'city'],
   [48, 55, 'postcode']]},
{'datapoint_id': 1,
  'text': 'land at 2a gerard street, ashton in makerfield, wigan (wn4 9aa)',
  'entities': [(0, 4, 'unit_type'),
   (11, 24, 'street_name'),
   (48, 53, 'city'),
   (55, 62, 'postcode')]},
 {'datapoint_id': 2,
  'text': 'unit 111, timber wharf, worsley street, manchester (m15 4nz)',
  'entities': [(0, 4, 'unit_type'),
   (5, 8, 'unit_id'),
   (10, 23, 'building_name'),
   (24, 38, 'street_name'),
   (40, 50, 'city'),
   (52, 59, 'postcode')]}]

In [61]:
nlp(test[0])

ValueError: [E866] Expected a string or 'Doc' as input, but got: <class 'dict'>.

In [40]:
doc = nlp(test[0]['text'])
gold_dict = test[0]['entities']
example = Example.from_dict(doc, {'entities':gold_dict})

example

In [42]:
type(example)

spacy.training.example.Example

In [65]:
!python -m spacy convert "/tf/empty_homes_data/humanloop_spacy_format.json" "/tf/empty_homes_data/spacy_data/"

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/usr/local/lib/python3.8/dist-packages/spacy/cli/_util.py", line 71, in setup_cli
    command(prog_name=COMMAND)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/spacy/cli/convert.py", line 75, in convert_cli
    convert(
  File "/usr/local/lib/python3.8/dist-packages/spacy/cli/convert.py", line 140, in convert
    db = DocBin(docs=docs, store_user_data=True)
  File "/usr/local/lib/python3.8/dist-packages/spacy/tokens/_serialize.py", line 86, in __init__
    for doc in docs:
  File "/usr/local/lib/python3.8/dist-packages/spacy/training/converters/json_to_docs.py", line 16, in json_to_docs
    for json_para in json_to_annotations(json_doc):
  File "spacy/training/gold_io.pyx", line 85, in json_to_annotations
KeyError: 'paragraphs'

In [3]:
from spacy.training import JsonlCorpus

corpus = JsonlCorpus("/tf/empty_homes_data/humanloop_spacy_format.json")
nlp = spacy.blank("en")
data = corpus(nlp)
doc_bin = DocBin(docs=data)

/usr/local/lib/python3.8/dist-packages/spacy/training/corpus.py:80: UserWarning: [W090] Could not locate any .jsonl files in path '/tf/empty_homes_data/humanloop_spacy_format.json'.
  warnings.warn(Warnings.W090.format(path=orig_path, format=file_type))

In [55]:
nlp = spacy.blank("en")
data = corpus(nlp)

In [56]:
doc_bin = DocBin(docs=data)

In [59]:
doc_bin.to_disk("/tf/empty_homes_data/spacy_data/training_data.spacy")